"""智能头盔集中配置。

所有硬件引脚、通信参数、算法阈值都放在这里，便于换板子或换服务器时集中修改。
"""

DEVICE_ID = "helmet_001"

# I2C
I2C_ID = 1
I2C_SCL_PIN = 22
I2C_SDA_PIN = 21
I2C_FREQ = 100000

# I2C sensor addresses
JX90614_ADDR = 0x7F
JX90614_I2C_FREQ = 100000
JX90614_ENABLE = True
SHT40_ADDR = 0x44
SHT40_ENABLE = True
BAROMETER_ADDR = 0x76
BAROMETER_ENABLE = True
GY302_ADDR = 0x23
GY302_ALT_ADDR = 0x5C
GY302_ENABLE = True

# UART GPS
GNSS_ENABLE = False
GPS_UART_ID = 1
GPS_TX_PIN = 17
GPS_RX_PIN = 16
GPS_BAUDRATE = 9600

# 4G UART
G4_UART_ID = 2
G4_TX_PIN = 26
G4_RX_PIN = 27
G4_BAUDRATE = 115200

# GPIO / ADC
BUZZER_PIN = 25
SOS_BUTTON_PIN = 32
CANCEL_BUTTON_PIN = 33
ULTRASONIC_TRIG_PIN = 18
ULTRASONIC_ECHO_PIN = 19
LIGHT_ADC_PIN = 34

# Uniknect 官方示例中 Pin 常用字符串名；如你的扩展板已经定义好名字，可在这里改。
BUZZER_PIN_NAME = None
SOS_BUTTON_PIN_NAME = None
CANCEL_BUTTON_PIN_NAME = None
ULTRASONIC_TRIG_PIN_NAME = None
ULTRASONIC_ECHO_PIN_NAME = None
LIGHT_ADC_PIN_NAME = None

# MQTT
COMM_UPLOAD_ENABLE = False
MQTT_ENABLE = True
MQTT_CLIENT_ID = DEVICE_ID
MQTT_BROKER = "101.37.104.185"
MQTT_PORT = 41552
MQTT_USERNAME = "quectel"
MQTT_PASSWORD = "12345678"
MQTT_TOPIC_DATA = "helmet/helmet_001/data"
MQTT_TOPIC_HEARTBEAT = "helmet/helmet_001/heartbeat"
MQTT_TOPIC_EVENT = "helmet/helmet_001/event"
MQTT_TOPIC_CMD = "helmet/helmet_001/cmd"
MQTT_TOPIC_STATUS = "helmet/helmet_001/status"

# Backward-compatible names used by older local code.
MQTT_TOPIC_TELEMETRY = MQTT_TOPIC_DATA
MQTT_TOPIC_WARNING = MQTT_TOPIC_EVENT

# Timing
SENSOR_UPDATE_MS = 100
UPLOAD_INTERVAL_MS = 1000
HEARTBEAT_INTERVAL_MS = 30000
GNSS_READ_INTERVAL_MS = 5000
MQTT_RECONNECT_INTERVAL_MS = 30000
COMM_CACHE_MAX = 20

# Algorithm debug output
ALGORITHM_DEBUG_ONLY = True
ALGORITHM_DEBUG_ENABLE = True
ALGORITHM_DEBUG_INTERVAL_MS = 1000
ALGORITHM_DEBUG_PRINT_NORMAL = True

# Thresholds
COLLISION_LIGHT_G = 2.5
COLLISION_MEDIUM_G = 4.0
COLLISION_SEVERE_G = 6.0
COLLISION_JERK_G_S = 20.0

HEAT_LIGHT_C = 35.0
HEAT_MEDIUM_C = 38.0
HEAT_SEVERE_C = 42.0

DISTANCE_LIGHT_CM = 100.0
DISTANCE_MEDIUM_CM = 60.0
DISTANCE_SEVERE_CM = 30.0
