"""预警状态码和等级定义。"""

WARNING_NONE = 0

COLLISION_SUSPECTED = 101
COLLISION_LIGHT = 102
COLLISION_MEDIUM = 103
COLLISION_SEVERE = 104

HEAT_WARNING_LIGHT = 201
HEAT_WARNING_MEDIUM = 202
HEAT_WARNING_SEVERE = 203

FATIGUE_SUSPECTED = 301
FATIGUE_CONFIRMED = 302

SOS_MANUAL = 401
SOS_AUTO = 402

DISTANCE_WARNING_LIGHT = 501
DISTANCE_WARNING_MEDIUM = 502
DISTANCE_WARNING_SEVERE = 503

LEVEL_NORMAL = "normal"
LEVEL_SUSPECTED = "suspected"
LEVEL_LIGHT = "light"
LEVEL_MEDIUM = "medium"
LEVEL_SEVERE = "severe"


def level_for_code(code):
    """根据预警码返回等级字符串。"""
    if code in (COLLISION_SEVERE, HEAT_WARNING_SEVERE, DISTANCE_WARNING_SEVERE):
        return LEVEL_SEVERE
    if code in (COLLISION_MEDIUM, HEAT_WARNING_MEDIUM, DISTANCE_WARNING_MEDIUM):
        return LEVEL_MEDIUM
    if code in (COLLISION_LIGHT, HEAT_WARNING_LIGHT, DISTANCE_WARNING_LIGHT):
        return LEVEL_LIGHT
    if code in (COLLISION_SUSPECTED, FATIGUE_SUSPECTED):
        return LEVEL_SUSPECTED
    return LEVEL_NORMAL

